# model needs the parameters while we use transfer leraning, params.yaml is used to mention that all

AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] 
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.0001